import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "@/styles/globals.css";

const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps) {

  return (
    <html lang="pt-br">
      <body className={`${gabarito.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
